@startwbs
* 巡查
** 录入
*** 整改通知书/监管意见书
**** UI
***** 基础信息
***** 意见和天数
***** 签名盖章及样式声效实现
***** 顶部按钮交互
***** 提交交互
***< 接口
***< 分享
** 管理(巡查人员)
*** 任务位置显示优化
*** 显示门店规模信息
*** 显示任务的剩余时间
*** 列表新增交互(企业详情/巡查拍照)入口
@endwbs
