@startuml
'新建甘特图
@startgantt
scale 2
page 1x1
title
        智慧通知里程碑甘特图
        创建时间: 2020-08-14 20:09
        endtitle
        left header
                通过甘特图梳理工作进度安排
                iOS 完成移动端详情UI/API前期联调
                需求调整：
                1. 详情页面附件模块
                2. 通知对象中门店选择器UI样式
        endheader
        project starts 2020-08-12
        Sunday are closed
        Saturday are closed
        [需求评审/UI评审] as [design] on {产品:100%} lasts 3 days
        [立项] happens at [design]'s end
        --移动端--
        then [创建->通知->详情] as [develop] on {移动端:100%} lasts 7 days
        [详情] as [detail] lasts 3 days
        [detail] starts at [develop]'s start
        then [选择对象] lasts 2 days
        then [发布通知]  lasts 2 days
        '前端进度
        [develop] is 100% completed

        --后台--
        [接口] as [api] on {后台组} lasts 7 days
        [API定义] as [define] lasts 2 days
        [详情API] as [detailAPi] lasts 2 days
        [新建API] as [newAPI] lasts 2 days
        [短信] as [duanxin] lasts 1 days
        '接口进度
        [api] is 100% completed

        --web端--
        [短信web] as [dxweb] on {web端} lasts 1 days
        --平台端--
        [平台API] as [pt] on {平台组} lasts 2 days
        [用户列表] as [guser] lasts 1 days
        [网格员] as [wguser] lasts 1 days
        '接口进度
        [pt] is 100% completed

        '关系
        design --> pt
        [guser] starts at [pt]'s start
        guser --> wguser

        design --> api
        [define] starts at [api]'s start
        define --> detailAPi
        detailAPi --> newAPI
        newAPI --> duanxin
        [dxweb] starts at [duanxin]'s start

        --提测发布--
        [集成联调] as [lt2] on {移动端:100%} {平台组} {后台组} lasts 1 days
        [系统测试] as [xitongces] on {测试} lasts 1 days
        [UI验收] as [UIcheck] on {UI组} lasts 1 days
        [xitongces] starts at [develop]'s end
        [UIcheck] starts at [develop]'s end
        [lt2] starts at [develop]'s end
        [lt2] starts at [api]'s end
        [自测] happens at [lt2]'s end
        [提测] as [test] on {测试:100%} lasts 3 days
        [test] starts at [lt2]'s end
        [测试] as [first] lasts 2 days
        [first] starts at [test]'s start
        then [正式] lasts 1 days
        [发布] happens at [正式]'s end
        @endgantt
@enduml
