@startuml
scale 1
title
        智慧通知选择对象类图活动图
        创建时间: 2020-08-13 20:10
        endtitle
        left header
                梳理门店/人员分页加载/全部加载配合全选的操作流程，归纳出合理的解决方案。
                概念：活动图本质上是一种流程图，它描述活动的序列，即系统从一个活动到另一个活动的控制流。
                作用：描述用例，描述类的操作，另外，可以用来描述算法（单独使用）。
        endheader
        '使用管道符号新建泳道
        |门店列表|
        |#bisque|门店搜索列表|

        |门店列表|
        start
        :门店列表;
        if (加载全部) then (YES)
                :所有数据;
                -[#blue]->
                |门店搜索列表|
                :本地搜索;
                -[#blue]->
                :搜索“金和”十条数据;
                -[#blue]->
                :历史记录中筛选;
                -[#blue]->
        else(分页加载)
        |门店列表|
        :加载十条;
        |门店搜索列表|
        if (接口搜索) then (YES)
                :接口搜索;
                :搜索“金和”十条数据;
                :接口返回新数据;
        else(本地搜索)
        :本地搜索;
        :搜索“金和”十条数据;
        :历史记录中筛选;
endif
endif
:选中搜索列表的三条;
|门店列表|
if (接口搜索) then (YES)
:去重操作;
:在历史记录中添加接口返回的三条数据;
else(本地搜索)
:更新历史记录的选中状态;
endif
:包含搜索的门店列表;

@enduml
