'新建甘特图
@startgantt
scale 2
page 1x1
title
        智慧通知里程碑甘特图
        创建时间: 2020-08-14 20:09
        endtitle
        left header
                通过甘特图梳理工作进度安排
        endheader
        project starts 2020-08-12
        Sunday are closed
        Saturday are closed
        [需求评审] as [design] on {产品:100%} lasts 3 days
        [立项] happens at [design]'s end
        --开发阶段--
        then [创建--发送--查看] as [develop] on {移动端:100%} lasts 7 days
        [详情] as [detail] lasts 3 days
        [detail] starts at [develop]'s start
        then [选择对象] lasts 2 days
        then [发送通知]  lasts 2 days
        [联调] as [lt2] on {移动端:100%} {平台} {后台} lasts 1 days
        [lt2] starts at [develop]'s end
        [自测] happens at [lt2]'s end
        --提测发布--
        [提测] as [test] on {测试:100%} lasts 4 days
        [test] starts at [lt2]'s end
        [测试] as [first] lasts 2 days
        [first] starts at [test]'s start
        then [正式] lasts 2 days
        [发布] happens at [正式]'s end
        @endgantt
