@startuml
scale 1
title
        Small路由框架的活动图
        创建时间: 2020-05-16 09:44
        endtitle
        left header
                梳理small的使用原理，解决加载framework获取printclass为nil的问题
                iOS之后，无法加载
                NSBundle无法读取NSPrincipalClass
        endheader
        '使用管道符号新建泳道
        |解析bundle.json文件|
        |#bisque|解析|
        |#beige|加载|
        |解析bundle.json文件|
        start
        :loadManifestWithPath:error:;
        :loadManifestWithPath:error:;
        :loadBundles:bundles;
        if (kLoadingComplection==nil) then (YES)
                :syncLoadBundles:;
        else(NO)
        :开子线程一步加载;
endif

|SMbundle|
:initWithDictionary:;
if (包含pkg) then (YES)
        if (.lib/.app) then (YES)
                :FrameWork包的解析;
                :bundleName;
                if(bundlefile已存在) then (YES)
                :解压文件;
                :移除压缩包;
                if(在document目录) then (YES)
                :补丁文件;
        elseif(在bundle目录)
        :库文件;
endif
:NSBundle initWithPath:加载bundle;
else(NO)
:;
endif
else(NO)
:其他资源包;
endif

:解析Framework类型;
else(NO)
:main模块;
endif


|加载|

@enduml
