@startuml
scale 0.5
page 1x1
title
    DesiginCode开发类图
    创建时间: 2019-12-26 21:16
    endtitle
    left header
        swiftUI开发使用
        概念：类是具有相同属性和行为的对象集合。
        作用：类图是描述类、接口已经他们之间关系的图，它显示了系统中各个类的静态结构，是一种静态模型。
    endheader

    'type:package，node，folder，frame，cloud，database
    folder "主页" as homepages{
        class "home" as home <?swift> {
            -- property --
            var body
            __func__
            func createDatas;
        }

    }

    @enduml
