@startuml
scale 1
title
        人脸识别和开锁业务活动图
        创建时间: 2020-07-08 22:30
        endtitle
        left header
                梳理js调用开锁的相关流程，失败成功的相关回调
                概念：活动图本质上是一种流程图，它描述活动的序列，即系统从一个活动到另一个活动的控制流。
                作用：描述用例，描述类的操作，另外，可以用来描述算法（单独使用）。
        endheader
        '使用管道符号新建泳道
        |人脸识别|
        |#bisque|开锁|
        |#beige|五定|

        |人脸识别|
        start
        if (蓝牙开启) then (YES)
                :人脸识别;
                if (成功) then (YES)
                        |开锁|
                        :搜索设备;
                        :链接设备;
                        :开锁设备;
                        :回调js成功逻辑;
                else(NO)
                :回调js失败逻辑;
        endif
        |人脸识别|
else(NO)
:提示用户开启蓝牙;
endif

|五定|
:活动;

@enduml
