@startuml
scale 2
page 1x1
title
    人员档案
    创建时间: <2019-12-04 20:54>
    endtitle
    left header
        完成设计
    endheader
    'package，node，folder，frame，cloud，database'
    folder "personalList" as listpkg{
        class "personBaseListViewController" as baselist {
            --var --
            NSString *Id;
            UITableView *tableView;
            __ func__
            -(void)loadData;
            -(void)refreshData;
        }
        class "PersonalListViewController" as personlist {
            --var--
            NSString *requestID;
            --func--
            -(void)createView;
        }
        baselist <|-- personlist:继承<
    }


    'package，node，folder，frame，cloud，database'
    folder "detail" as detail{
        class "personalDetailBaseViewContrller" as detailBase {
            --var --

            __func __
        }
        class "personalDetailViewContoller" as personaldetail {
            --var --
            UIView *headView;
            UIView *secondView;
            __ func__
            -(void)loadData;
        }

        detailBase <|-- personaldetail:继承<
       
    }

    @enduml
