@startuml
scale 1
page 1x1
title
        直通老板用例图
        创建时间: 2020-07-21 23:10
        endtitle
        left header
                通过用例梳理开发功能项，熟悉老板任务，迭代新版任务
                用例是用户期望系统具备的功能，每一个用例说明一个系统提供给它的使用者的一种服务或功能。
                用例的目标是要定义系统的一个行为，但并不显示系统的内部结构。
                用例图定义和描述了系统的外部可见行为，是分析、设计直至组装测试的重要依据
        endheader

        :我: as admin
        usecase map as "
        ==**平安地图/地图用例**==
        定位直播门店，进入直通老板页面
        --基础操作流程--
        选中，进入门店详情，直通老板/上报--进入直通负责人
        ..可选操作流程..
        可选操作
        "

        'workflow
        admin -right-> map:地图


        @enduml
